BHS/pertaminalpg-web/LPG/Models/List.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> ExpireAt { get; set; }
    }
}

BHS/pertaminalpg-web/LPG/Models/NotificationLog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public long LogId { get; set; }
        public string ReceiverId { get; set; }
        public string JSONMessage { get; set; }
        public string FCMResponse { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string MobileNumber { get; set; }
        public string UserRole { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Failure { get; set; }
        public Nullable<short> IsRead { get; set; }
        public Nullable<System.DateTime> ReadAt { get; set; }
    }
    public Nullable<int> UserId { get; set; }

    public string UserName { get; set; }

    public string MobileNumber { get; set; }

    public string UserRole { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public Nullable<int> Success { get; set; }

    public Nullable<int> Failure { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<short> IsRead { get; set; }

    public Nullable<System.DateTime> ReadAt { get; set; }

}

BHS/pertaminalpg-web/LPG/Controllers/NotificationLogController.cs
using LPG.App_Classes;
using LPG.App_Services;
using LPG.Models;
using LPG.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using ClosedXML.Excel;
using System.Globalization;
using i18n;
using LPG.Reporting.ReportServices;



namespace LPG.Controllers
{
    public class NotificationLogController : AbstractController<INotificationHistoryService>
    {
        SessionManagement sessionManagement;
        private const string SESSION_TIME_OUT = "SESSION_TIMEOUT";

        public NotificationLogController(
            INotificationHistoryService _serviceObject
            ) : base(_serviceObject)
        {

        }
        
        // GET: NotificationLog
        public ActionResult List()
        {
            try
            {
                sessionManagement = new SessionManagement();
                AdminSessionEntity adminSessionInfo = sessionManagement.getAdminSession();
                ViewBag.Role = adminSessionInfo.UserRole;
                if (adminSessionInfo != null)
                {
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                telemectryClient.TrackException(ex);
                ExceptionHelper.Log(ex);
                return RedirectToAction("Index", "Error", new { area = "Products List" });
            }
            
        }
        [HttpPost]
        public ActionResult List(DatatablesRequest model)
        {
            try
            {
                sessionManagement = new SessionManagement();
                AdminSessionEntity adminSessionInfo = sessionManagement.getAdminSession();
                ViewBag.Role = adminSessionInfo.UserRole;
                if (adminSessionInfo != null)
                {
                    var result = serviceObject.GetList(model);
                    return Json(result);
                }
                else
                {
                    return Json(null);
                }
            }
            catch (Exception ex)
            {
                telemectryClient.TrackException(ex);
                ExceptionHelper.Log(ex);
                return Json(null);
            }
        }

        [HttpPost]
        public ActionResult Export()
        {
            try
            {
                sessionManagement = new SessionManagement();
                AdminSessionEntity adminSessionInfo = sessionManagement.getAdminSession();
                ViewBag.Role = adminSessionInfo.UserRole;
                if (adminSessionInfo != null)
                {
                    lpgdevEntities entities = new lpgdevEntities();
                    DataTable dt = new DataTable("MasterData");
                    dt.Columns.AddRange(new DataColumn[] {
                        new DataColumn("[[[No]]]"),
                        new DataColumn("[[[Username]]]"),
                        new DataColumn("[[[MobileNumber]]]"),
                        new DataColumn("[[[Role]]]"),
                        new DataColumn("[[[Agen]]]"),
                        new DataColumn("[[[Judul]]]"),
                        new DataColumn("[[[Pesan]]]"),
                        new DataColumn("[[[TerkirimPada]]]"),
                        new DataColumn("[[[Status Pengiriman]]]"),
                        new DataColumn("[[[Dibuka]]]"),
                        new DataColumn("[[[Dibuka Pada]]]")
                    });

                    var notifications = serviceObject.GetAll();
                    
                    int count = 0;
                    foreach (var notification in notifications)
                    {
                        count++;

                        var date = string.Empty;
                        var readdate = string.Empty;
                        var statusPengiriman = "Pengiriman Gagal";
                        var dibaca = "Sudah Dibaca";

                        if (notification.CreatedDate != null)
                        {
                            date = notification.CreatedDate.Value.ToString("dd/MM/yyyy HH:mm");
                        }

                        if (notification.ReadAt != null)
                        {
                            //notification.ReadAt.Value;
                            var rddate = new DateTime(notification.ReadAt.Value.Year, notification.ReadAt.Value.Month, notification.ReadAt.Value.Day, notification.ReadAt.Value.Hour, notification.ReadAt.Value.Minute, notification.ReadAt.Value.Second, DateTimeKind.Utc);
                            readdate = TimeZoneInfo.ConvertTimeBySystemTimeZoneId(rddate, "SE Asia Standard Time").ToString("dd/MM/yyyy HH:mm");
                        }

                        if (notification.Success != null)
                        {
                            statusPengiriman = notification.Success.Value > 0? "Pengiriman Berhasil": "Pengiriman Gagal";
                        }

                        if (notification.IsRead != null)
                        {
                            dibaca = notification.IsRead.Value == 0 ? "Belum DIbaca" : "Sudah Dibaca";
                        }

                        dt.Rows.Add
                        (
                            count,
                            notification.Username,
                            notification.MobileNumber,
                            notification.Role,
                            notification.NamaAgen,
                            notification.Title,
                            notification.Message,
                            date,
                            statusPengiriman,
                            dibaca,
                            readdate
                            
                       );
                    }
                    var style = XLWorkbook.DefaultStyle;


                    using (XLWorkbook wb = new XLWorkbook())
                    {


                        wb.Worksheets.Add(dt);
                        using (MemoryStream stream = new MemoryStream())
                        {
                            wb.SaveAs(stream);
                            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Notification History.xlsx");
                        }
                    }
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception ex)
            {
                telemectryClient.TrackException(ex);
                ExceptionHelper.Log(ex);
                return RedirectToAction("Index", "Error", new { area = "Products List" });
            }

        }
    }
}

BHS/pertaminalpg-web/LPG/Views/NotificationLog/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}


<link href="~/Content/css/toastr.css" rel="stylesheet" />
<script src="~/Scripts/moment.min.js"></script>
<script src="~/Scripts/toastr.js"></script>
<div class="content-wrapper py-3">
    <div class="page-header">
        <div><span class="page-name">[[[Notification History]]]</span></div>
    </div>
    <div class="container-fluid">
        <div class="row" style="margin-bottom:10px;">
            <div class="col-md-12">
                @using (Html.BeginForm("Export", "NotificationLog", FormMethod.Post))
                {
                    <button type="submit" class="btn btn-success btn-sm">[[[Export Excel]]]</button>
                }
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover col-valign" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>[[[Username]]]</th>
                        <th>[[[Mobile Number]]]</th>
                        <th>[[[Role]]]</th>
                        <th>[[[Agen]]]</th>
                        <th>[[[Judul]]]</th>
                        <th>[[[Pesan]]]</th>
                        <th>[[[Terkirim Pada]]]</th>
                        <th>[[[Status Pengiriman]]]</th>
                        <th>[[[Dibuka]]]</th>
                        <th>[[[Dibuka Pada]]]</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
<script>
    moment.locale('id');
    $(document).ready(function () {
        $('#dataTable').DataTable({

            "pagingType": "full_numbers",
            "scrollX": true,
            "language": {
                "url": "/Content/datatables/indonesia.json"
            },
            "columnDefs": [
                { defaultContent: '-', targets: '_all' },
                {
                    data: 'Username',
                    targets: 0
                },
                {
                    data: 'MobileNumber',
                    targets: 1
                },
                {
                    data: 'Role',
                    targets: 2
                },
                {
                    data: 'NamaAgen',
                    targets: 3
                },
                {
                    data: 'Title',
                    targets: 4
                },
                {
                    data: 'Message',
                    targets: 5
                },
                {
                    data: 'CreatedDateFormated',
                    targets: 6,
                    render: function (data, type, row) {
                        if (row.CreatedDateFormated)
                            //return moment(new Date((row.CreatedDate.match(/\d+/)[0] * 1))).format('DD/MM/YYYY HH:mm');
                            //return moment((new Date((row.CreatedDate.match(/\d+/)[0] * 1))).toISOString(), 'YYYY-MM-DDTHH:mm:ss').format('DD/MM/YYYY HH:mm')
                            //return convertDateFormat(new Date((row.CreatedDate.match(/\d+/)[0] * 1)));
                            return moment(row.CreatedDateFormated, 'YYYY-MM-DDTHH:mm:ss').format('DD/MM/YYYY HH:mm');
                        else
                            return '-';
                    }
                },
                {
                    data: 'Success',
                    targets: 7,
                    render: function (data, type, row) {
                        if (row.Success > 0)
                            return 'Pengiriman Berhasil'
                        else
                            return 'Pengiriman Gagal';
                    }
                },
                {
                    data: 'IsRead',
                    visible:false,
                    targets: 8,
                    render: function (data, type, row) {
                        if (row.IsRead == 0)
                            return 'Belum dibaca'
                        else
                            return 'Sudah dibaca';
                    }
                },
                {
                    data: 'ReadAtFormated',
                    visible: false,
                    targets: 9,
                    render: function (data, type, row) {
                        if (row.ReadAtFormated)
                            //return moment(new Date((row.CreatedDate.match(/\d+/)[0] * 1))).format('DD/MM/YYYY HH:mm');
                            //return moment.utc(moment.utc((new Date((row.ReadAt.match(/\d+/)[0] * 1)))).local().format('YYYY-MM-DD HH:mm:ss')).local().format('YYYY/MM/DD HH:mm')
                            return moment(row.ReadAtFormated, 'YYYY-MM-DDTHH:mm:ss').format('DD/MM/YYYY HH:mm');
                        else
                            return '-';
                    }
                }
            ],
            serverSide: true,
            ajax: {

                url: '/NotificationLog/List',
                type: "POST",
                dataType: 'json',
                async: true,
                contentType: 'application/json',
                data: function (data) {

                    var x = {};

                    x.draw = data.draw;
                    x.length = data.length;
                    x.search = [data.search.value];
                    x.start = (data.start / data.length);

                    return JSON.stringify(x); // return JSON string
                },
                processing: true,
                //dataSrc: function (data) {
                //    return data.data;
                //},
                searchDelay: 350,

            }
        });
    });

    function convertDateFormat(date) {
        var today = date; var dd = today.getDate(); var mm = today.getMonth() + 1; //January is 0! 
        var hour = today.getHours();
        var min = today.getMinutes();
        var yyyy = today.getFullYear();
        if (dd < 10) { dd = '0' + dd }
        if (mm < 10) { mm = '0' + mm }
        if (hour < 10) { hour = '0' + hour }
        if (min < 10) { min = '0' + min }
        var today = dd + '/' + mm + '/' + yyyy + ' '+hour+':'+min;
        return today;
    }

</script>